ARG VERSION
FROM alpine AS files
COPY config/php/apache/php.ini /php/usr/local/etc/php/php.ini
COPY files/php/wyga/wyga-entrypoint.sh /php/
COPY files/wyga/env-conf.bash /php/usr/local/bin/env-conf
RUN chmod +x /php/wyga-entrypoint.sh /php/usr/local/bin/env-conf
RUN mkdir -p /php/app/public

FROM wyga/php:$VERSION-upstream
COPY --from=files /php/ /

WORKDIR /app
ENTRYPOINT [ "/wyga-entrypoint.sh" ]
CMD [ "php-fpm" ]
