ARG VERSION
FROM alpine AS files
COPY files/pma/db /db/
WORKDIR /db/
RUN chmod +x generate-payload.sh && \
  ./generate-payload.sh >pma-init.sh && \
  chmod -x pma-init.sh
FROM mariadb:${VERSION}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
    apt-get dist-upgrade -qq && \
    apt-get clean all && \
    find /var/lib/apt/lists/ -type f -delete

COPY --from=files /db/pma-init.sh /docker-entrypoint-initdb.d/
STOPSIGNAL SIGSTOP
